### ISSUE TITLE
Recognize files in vendor

### ISSUE THREAD

**Issue by jostyee** [sourcegraph/sourcegraph-sublime#1]
I want to view a vendor file in srcgraph but get 500 error, the url is: 

https://sourcegraph.com/-/editor?end_col=30&branch=11-refactoring-codes&start_row=255&version=v1.0.4&end_row=255&file=vendor%2Fgithub.com%2Fgo-playground%2Flog%2Flog.go&editor=Sublime&start_col=30&remote_url=git%2Bssh%3A%2F%2Fgit%40$MY_REPO

So I guess the plugin should send the import path of vendor dep as `remote_url` param?

**Comment by emidoots** [comment]
Hi @jostyee ! First, apologies for the delay on getting back to you on this!

The `remote_url` actually comes from your Git repository itself, e.g. the output of `git remote get-url origin`; From this Sourcegraph can bring you to the right GitHub repository.

There are three problems here:

1. In your case here, the `remote_url` is `git+ssh://git@$MY_REPO` which is a bit strange (unless you redacted that from your message). Could you try cloning the repo again or setting the URL via `git remote set-url origin <url>` so that it points to a valid repository?
2. Fixed ~~That error page is lacking this information -> I'll fix this very soon.~~
3. ~~We don't currently support the `git+ssh` protocol, I'll add support for this very soon.~~ EDIT: Actually, that doesn't seem to be a valid remote protocol at all?

**Comment by emidoots** [comment]
I've fixed point 2 above. Since this issue has become stale, I'm going to close it. Please feel free to open a new issue if you still encounter issues after correcting the Git remote URL in your repo :)
